### PR TITLE
Fix #1

### LINKED ISSUE #1: Some touch events not occuring at proper coordinates
I have an app that uses a grid of buttons and I noticed when using your code, at times when repeatedly pressing a button, the click would jump to a different button.   Using the evtest tool, I tracked these events down to cases when either the X or Y or both the X and Y coordinates would not change and the events in the pitft_touchscreen tool were coming in with a None value for X or Y (evdev is stateful, so this behavior makes sense).

In your current code, when this occurs you seem to be grabbing the replacement value from pygame, but is seems that the coordinates are sometimes not the same as the press location if the last event is a button_up event.   I re-wrote the code and got it working by storing historical values so the events missing the X and Y (or in some cases when the tap is in the exact same place, both comeback as None) are replaced with stateful equivalents.

Please let me know if this is something you want to possibly change in your library or have a better way to keep the coordinates stateful.  (I didn't test this completely as I have the code running in a separate class using class variables as well as in Python 2.7, but the concepts should be the same).   

I can say that now my touch locations are always consistent.

```
import pygame,pitft_touchscreen
from pygame.locals import *
pitft=pitft_touchscreen.pitft_touchscreen()
pitft.pigameevs=[]
pitft.es = 0
pitft.pl = {'x': False, 'y': False}

def init(rotation:int=90):
    pitft.pigamerotr=rotation
    pitft.start()

def run():
    while not pitft.queue_empty():
        for r in pitft.get_event():
            # Set the pygame event coordinates to the last settings.  This
            # allows us to handle the case where a click occurred in the
            # same spot on one or both of the axes.
            e = {'y': pitft.pl['y'], 'x': pitft.pl['x']}
            if r['x'] is not None:
                e['y'] = r['x']
            if r['y'] is not None:
                e['x'] = r['y']
            # If there is still no X & Y coordinates and nothing 
            # historical, throw away the event....
            if e['x'] is None or e['y'] is None:
                break
            if pitft.pigamerotr==90:
                e={"x":e["x"],"y":240-e["y"]}
            elif pitft.pigamerotr==270:
                e={"x":320-e["x"],"y":e["y"]}
            else:
                raise(Exception("PiTft rotation is unsupported"))
            d={}
            t=MOUSEBUTTONUP if r['touch'] == 0 else (
                    MOUSEBUTTONDOWN if pitft.es == 0 else MOUSEMOTION)
            if t==MOUSEBUTTONDOWN:
                pitft.es=1
                d["button"]=1
                d["pos"]=(e["x"],e["y"])
                pygame.mouse.set_pos(e["x"],e["y"])
            elif t==MOUSEBUTTONUP:
                pitft.es = 0
                d["button"]=1
                d["pos"]=(e["x"],e["y"])
            else:
                d["buttons"]=(True,False,False)
                d["rel"]=(0,0)
                d["pos"]=(e["x"],e["y"])
                pygame.mouse.set_pos(e["x"],e["y"])
            pe=pygame.event.Event(t,d)
            pygame.event.post(pe)
def quit():
    pitft.stop()
```

### PR DESCRIPTION
**Pull request by nift4**
Fixes #1 
Review and test needed!

### CODE REVIEW

**Comment by BroMarduk** [comment]
OK, I tested this and it works regarding the events occurring correctly, but I did find another issue.

Currently the code creates an array to store a list of events (pitft.pigameevs=[]).  This array just keeps growing is size as items are never removed.  EVDEV will eventually wrap around (I think the id is an integer) and there will be conflicts with duplicates.

I think the goal is to detect the MOUSEMOTION event from MOUSEBUTTONDOWN.   A better way would be to just keep the buttondown/up state and toggle the state accordingly on a touch or lift.   No more ever-growing array and it correctly distinguishes between events. 

If you have another reason for storing the event IDs, let me know.

```
import pygame,pitft_touchscreen
from pygame.locals import *
pitft=pitft_touchscreen.pitft_touchscreen()
pitft.button_state=0
pitft.pl={'x':0,'y':0}
def init(rotation:int=90):
    pitft.pigamerotr=rotation
    pitft.start()
def run():
    while not pitft.queue_empty():
        for r in pitft.get_event():
            e={"y":(r["x"] if r["x"] else pitft.pl["x"]),"x":(r["y"] if r["y"] else pitft.pl["y"])}
            if e["x"] is None or e["y"] is None:
                break
            rel=(e["x"]-pitft.pl["x"],e["y"]-pitft.pl["y"])
            pitft.pl={"x":e["x"],"y":e["y"]}
            if pitft.pigamerotr==90:
                e={"x":e["x"],"y":240-e["y"]}
            elif pitft.pigamerotr==270:
                e={"x":320-e["x"],"y":e["y"]}
            else:
                raise(Exception("PiTft rotation is unsupported"))
            d={}
            t=MOUSEBUTTONUP if r["touch"]==0 else (MOUSEBUTTONDOWN if pitft.button_state == 0 else MOUSEMOTION)
            if t==MOUSEBUTTONDOWN:
                pitft.button_state = 1
                d["button"]=1
                d["pos"]=(e["x"],e["y"])
                pygame.mouse.set_pos(e["x"],e["y"])
            elif t==MOUSEBUTTONUP:
                pitft.button_state = 0
                d["button"]=1
                d["pos"]=(e["x"],e["y"])
            else:
                d["buttons"]=(True,False,False)
                d["rel"]=rel
                d["pos"]=(e["x"],e["y"])
                pygame.mouse.set_pos(e["x"],e["y"])
            pe=pygame.event.Event(t,d)
            pygame.event.post(pe)
def quit():
    pitft.stop()
```

If you want to create a branch and give me permission to edit in it, I can change code directly there.

**Comment by nift4** [comment]
I have a branch, but how allow editing?

**Comment by nift4** [comment]
Branch deleted, please make a fork! It's not easy on GitHub to do permission management per branch

**Comment by BroMarduk** [comment]
Will do.

**Pull request merged**
